const movies = [
  {
    Title: 'No Time to Die',
    Year: '2021',
    Rated: 'PG-13',
    Released: '08 Oct 2021',
    Runtime: '163 min',
    Genre: 'Action, Adventure, Thriller',
    Director: 'Cary Joji Fukunaga',
    Writer: 'Neal Purvis, Robert Wade, Cary Joji Fukunaga',
    Actors: 'Daniel Craig, Ana de Armas, Rami Malek',
    Plot: 'Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.',
    Language: 'English, French, Italian, Russian, Spanish, German',
    Country: 'United Kingdom, United States',
    Awards: 'Nominated for 3 Oscars. 30 wins & 64 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYWQ2NzQ1NjktMzNkNS00MGY1LTgwMmMtYTllYTI5YzNmMmE0XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.3/10' },
      { Source: 'Rotten Tomatoes', Value: '83%' },
      { Source: 'Metacritic', Value: '68/100' },
    ],
    Metascore: '68',
    imdbRating: '7.3',
    imdbVotes: '327,161',
    imdbID: 'tt2382320',
    Type: 'movie',
    DVD: '09 Nov 2021',
    BoxOffice: '$160,891,007',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Up',
    Year: '2009',
    Rated: 'PG',
    Released: '29 May 2009',
    Runtime: '96 min',
    Genre: 'Animation, Adventure, Comedy',
    Director: 'Pete Docter, Bob Peterson',
    Writer: 'Pete Docter, Bob Peterson, Tom McCarthy',
    Actors: 'Edward Asner, Jordan Nagai, John Ratzenberger',
    Plot: 'As a boy, Carl Fredricksen wanted to explore South America and find the forbidden Paradise Falls. About 64 years later he gets to begin his journey along with Boy Scout Russell by lifting his house with thousands of balloons. On their journey, they make many new friends including a talking dog, and figure out that someone has evil plans. Carl soon realizes that this evildoer is his childhood idol.',
    Language: 'English',
    Country: 'United States',
    Awards: 'Won 2 Oscars. 79 wins & 87 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.2/10' },
      { Source: 'Rotten Tomatoes', Value: '98%' },
      { Source: 'Metacritic', Value: '88/100' },
    ],
    Metascore: '88',
    imdbRating: '8.2',
    imdbVotes: '1,005,054',
    imdbID: 'tt1049413',
    Type: 'movie',
    DVD: '10 Nov 2009',
    BoxOffice: '$293,004,164',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'A Bronx Tale',
    Year: '1993',
    Rated: 'R',
    Released: '01 Oct 1993',
    Runtime: '121 min',
    Genre: 'Crime, Drama',
    Director: 'Robert De Niro',
    Writer: 'Chazz Palminteri',
    Actors: 'Robert De Niro, Chazz Palminteri, Lillo Brancato',
    Plot: "The Bronx, New York, 1960. 9-year-old Calogero grows up admiring and fascinated by the local mob boss, Sonny. Calogero's father, Lorenzo, wants to have nothing to do with the mob and does his best to keep his son away from Sonny and mob business. However, it may prove a losing battle.",
    Language: 'English, Italian',
    Country: 'United States',
    Awards: '1 win & 3 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTczOTczNjE3Ml5BMl5BanBnXkFtZTgwODEzMzg5MTI@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.8/10' },
      { Source: 'Rotten Tomatoes', Value: '97%' },
      { Source: 'Metacritic', Value: '80/100' },
    ],
    Metascore: '80',
    imdbRating: '7.8',
    imdbVotes: '137,497',
    imdbID: 'tt0106489',
    Type: 'movie',
    DVD: '11 Jan 2010',
    BoxOffice: '$17,287,898',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Wolf of Wall Street',
    Year: '2013',
    Rated: 'R',
    Released: '25 Dec 2013',
    Runtime: '180 min',
    Genre: 'Biography, Comedy, Crime',
    Director: 'Martin Scorsese',
    Writer: 'Terence Winter, Jordan Belfort',
    Actors: 'Leonardo DiCaprio, Jonah Hill, Margot Robbie',
    Plot: 'In the early 1990s, Jordan Belfort teamed with his partner Donny Azoff and started brokerage firm Stratton Oakmont. Their company quickly grows from a staff of 20 to a staff of more than 250 and their status in the trading community and Wall Street grows exponentially. So much that companies file their initial public offerings through them. As their status grows, so do the amount of substances they abuse, and so do their lies. They draw attention like no other, throwing lavish parties for their staff when they hit the jackpot on high trades. That ultimately leads to Belfort featured on the cover of Forbes Magazine, being called "The Wolf Of Wall St.". With the FBI onto Belfort\'s trading schemes, he devises new ways to cover his tracks and watch his fortune grow. Belfort ultimately comes up with a scheme to stash their cash in a European bank. But with the FBI watching him like a hawk, how long will Belfort and Azoff be able to maintain their elaborate wealth and luxurious lifestyles?',
    Language: 'English, French',
    Country: 'United States',
    Awards: 'Nominated for 5 Oscars. 37 wins & 179 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.2/10' },
      { Source: 'Rotten Tomatoes', Value: '79%' },
      { Source: 'Metacritic', Value: '75/100' },
    ],
    Metascore: '75',
    imdbRating: '8.2',
    imdbVotes: '1,327,178',
    imdbID: 'tt0993846',
    Type: 'movie',
    DVD: '25 Mar 2014',
    BoxOffice: '$116,900,694',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Social Network',
    Year: '2010',
    Rated: 'PG-13',
    Released: '01 Oct 2010',
    Runtime: '120 min',
    Genre: 'Biography, Drama',
    Director: 'David Fincher',
    Writer: 'Aaron Sorkin, Ben Mezrich',
    Actors: 'Jesse Eisenberg, Andrew Garfield, Justin Timberlake',
    Plot: 'On a fall night in 2003, Harvard undergrad and computer programming genius Mark Zuckerberg sits down at his computer and heatedly begins working on a new idea. In a fury of blogging and programming, what begins in his dorm room soon becomes a global social network and a revolution in communication. A mere six years and 500 million friends later, Mark Zuckerberg is the youngest billionaire in history... but for this entrepreneur, success leads to both personal and legal complications.',
    Language: 'English, French',
    Country: 'United States',
    Awards: 'Won 3 Oscars. 172 wins & 186 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOGUyZDUxZjEtMmIzMC00MzlmLTg4MGItZWJmMzBhZjE0Mjc1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.7/10' },
      { Source: 'Rotten Tomatoes', Value: '96%' },
      { Source: 'Metacritic', Value: '95/100' },
    ],
    Metascore: '95',
    imdbRating: '7.7',
    imdbVotes: '675,113',
    imdbID: 'tt1285016',
    Type: 'movie',
    DVD: '11 Jan 2011',
    BoxOffice: '$96,962,694',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: '3 Idiots',
    Year: '2009',
    Rated: 'PG-13',
    Released: '25 Dec 2009',
    Runtime: '170 min',
    Genre: 'Comedy, Drama',
    Director: 'Rajkumar Hirani',
    Writer: 'Rajkumar Hirani, Abhijat Joshi, Vidhu Vinod Chopra',
    Actors: 'Aamir Khan, Madhavan, Mona Singh',
    Plot: "Farhan Qureshi and Raju Rastogi want to re-unite with their fellow collegian, Rancho, after faking a stroke aboard an Air India plane, and excusing himself from his wife - trouser less - respectively. Enroute, they encounter another student, Chatur Ramalingam, now a successful businessman, who reminds them of a bet they had undertaken 10 years ago. The trio, while recollecting hilarious antics, including their run-ins with the Dean of Delhi's Imperial College of Engineering, Viru Sahastrabudhe, race to locate Rancho, at his last known address - little knowing the secret that was kept from them all this time.",
    Language: 'Hindi, English',
    Country: 'India',
    Awards: '63 wins & 26 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNTkyOGVjMGEtNmQzZi00NzFlLTlhOWQtODYyMDc2ZGJmYzFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.4/10' },
      { Source: 'Rotten Tomatoes', Value: '100%' },
      { Source: 'Metacritic', Value: '67/100' },
    ],
    Metascore: '67',
    imdbRating: '8.4',
    imdbVotes: '379,317',
    imdbID: 'tt1187043',
    Type: 'movie',
    DVD: '26 Apr 2011',
    BoxOffice: '$6,532,874',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'La La Land',
    Year: '2016',
    Rated: 'PG-13',
    Released: '25 Dec 2016',
    Runtime: '128 min',
    Genre: 'Comedy, Drama, Music',
    Director: 'Damien Chazelle',
    Writer: 'Damien Chazelle',
    Actors: 'Ryan Gosling, Emma Stone, Rosemarie DeWitt',
    Plot: 'Aspiring actress serves lattes to movie stars in between auditions and jazz musician Sebastian scrapes by playing cocktail-party gigs in dingy bars. But as success mounts, they are faced with decisions that fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.',
    Language: 'English, Cantonese',
    Country: 'United States, Hong Kong',
    Awards: 'Won 6 Oscars. 243 wins & 297 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.0/10' },
      { Source: 'Rotten Tomatoes', Value: '91%' },
      { Source: 'Metacritic', Value: '94/100' },
    ],
    Metascore: '94',
    imdbRating: '8.0',
    imdbVotes: '557,221',
    imdbID: 'tt3783958',
    Type: 'movie',
    DVD: '25 Apr 2017',
    BoxOffice: '$151,101,803',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Forrest Gump',
    Year: '1994',
    Rated: 'PG-13',
    Released: '06 Jul 1994',
    Runtime: '142 min',
    Genre: 'Drama, Romance',
    Director: 'Robert Zemeckis',
    Writer: 'Winston Groom, Eric Roth',
    Actors: 'Tom Hanks, Robin Wright, Gary Sinise',
    Plot: "Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His 'mama' teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone.",
    Language: 'English',
    Country: 'United States',
    Awards: 'Won 6 Oscars. 50 wins & 75 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.8/10' },
      { Source: 'Rotten Tomatoes', Value: '70%' },
      { Source: 'Metacritic', Value: '82/100' },
    ],
    Metascore: '82',
    imdbRating: '8.8',
    imdbVotes: '1,967,601',
    imdbID: 'tt0109830',
    Type: 'movie',
    DVD: '28 Aug 2001',
    BoxOffice: '$330,455,270',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Shawshank Redemption',
    Year: '1994',
    Rated: 'R',
    Released: '14 Oct 1994',
    Runtime: '142 min',
    Genre: 'Drama',
    Director: 'Frank Darabont',
    Writer: 'Stephen King, Frank Darabont',
    Actors: 'Tim Robbins, Morgan Freeman, Bob Gunton',
    Plot: "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.",
    Language: 'English',
    Country: 'United States',
    Awards: 'Nominated for 7 Oscars. 21 wins & 43 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.3/10' },
      { Source: 'Rotten Tomatoes', Value: '91%' },
      { Source: 'Metacritic', Value: '81/100' },
    ],
    Metascore: '81',
    imdbRating: '9.3',
    imdbVotes: '2,559,562',
    imdbID: 'tt0111161',
    Type: 'movie',
    DVD: '21 Dec 1999',
    BoxOffice: '$28,767,189',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
];

export function getMovies() {
  return movies;
}
